# Tegar Naufal Hanip - tegarnauf_19

# Menggunakan API Kubernetes versi 'apps/v1'.
# Penggunaan versi 'apps/v1' dikarenakan object Deployment memiliki API group-nya sendiri sehingga bukan bagian dari API inti.
apiVersion: apps/v1

# Menentukan Kubernetes object yang digunakan, yaitu Deployment
kind: Deployment

# Informasi mengenai resource pod
metadata:
  # Mendefinisikan nama dari pod App (front-end)
  name: karsajobs-frontend
  # Mendefinisikan label seperti nama label dan tier yang digunakan oleh pod
  labels:
    app: karsajobs
    tier: frontend

# Menentukan spesifikasi dari pod
spec:
  # Menentukan replica (jumlah Pod yang identik) dari pod berjumlah 1
  replicas: 1
  # Menentukan selector untuk mengidentifikasi pod
  selector:
    # selector yang digunakan yaitu yang memiliki label app karsajobs dan tier frontend
    matchLabels:
      app: karsajobs
      tier: frontend

  # Menentukan template pod seperti metadata dan spec container
  template:
    # Metadata dari template pod (sama dengan metadata labels sebelumnya)
    metadata:
      labels:
        app: karsajobs
        tier: frontend

    # Berisi spesifikasi container
    spec:
      containers:
        # nama dari cointainer
        - name: karsajobs-frontend
          # menggunakan image dari github package
          image: ghcr.io/tegarnh/a433-microservices/karsajobs-ui:latest
          # mendefisikan port yang akan digunakan container
          ports:
            - containerPort: 8000
